### ISSUE TITLE
linux下存放文件位置有问题

### ISSUE THREAD

**Issue by PackageInstaller** [Perseus037/nonebot_plugin_babattleline#1]
![image](https://github.com/Perseus037/nonebot_plugin_babattleline/assets/80018096/041e87e4-008f-4262-b125-5b33b405a727)
如图，会放到bot根目录下（（

**Comment by PackageInstaller** [comment]
好吧，看了下源码，直接改位置就好（

**Comment by Perseus037** [comment]
顺利解决就好（）

**Comment by PackageInstaller** [comment]
> 顺利解决就好（）

 不过如果能适配，或者直接放到bot的data目录下对应文件夹更好（
